### PR TITLE
Move block and method args to their own methods

### LINKED ISSUE #635: Slow backtraces due to inspect of large local variables
**Your environment**
* `ruby -v`: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
* `rdbg -v`: rdbg 1.5.0

**Describe the bug**
Backtraces are very slow at some points.  I added logging and was able to pin the slowness to `frame_info.rb` in `parameters_info`:
```
          local_var = local_variable_get(var)
          t1 = Time.now
          value = DEBUGGER__.safe_inspect(local_var, short: true)
          t2 = Time.now - t1
          if t2 > 0.1
            ::DEBUGGER__.info  "Slow parameters info, safe inspect... length: #{local_var.inspect.length}, type: #{local_var.class}, var: #{var}, value: #{value}, time#{t2}"
          end
```

This resulted in some output for slow parameters like the following:
```
DEBUGGER (INFO): Slow parameters info, safe inspect... length: 11729953, type: Hash, var: env, value: {"rack.version"=>[1, 6], "rack.errors"=>..., time0.321832
DEBUGGER (INFO): Slow parameters info, safe inspect... length: 11729955, type: Array, var: args, value: [{"rack.version"=>[1, 6], "rack.errors"=..., time0.436716
```
I believe the slowness is attributed to the `obj.inspect` in the safe_inspect.  I have a stack with 100+ depth which is resulting in about 25 seconds for the backtrace to return due to slowness on a bunch of frames (most seem to be with the env variable).  With the dap_client it doesn't even look like the parameters are used, so it feels a bit pointless retrieving these.  However the thread_client however does use this to output the shortened info.  Here's a sample output on the rdbg session for one of the slow entries:
```
  #35	Rails::Engine#call(env={"rack.version"=>[1, 6], "rack.errors"=>...) at ~/.gem/ruby/3.1.2/gems/railties-7.0.2.4/lib/rails/engine.rb:530
```

**To Reproduce**
I'm not super clear what's unique about the environment, but it's something to do with having a very large environment variable that causes this type of behavior.  I was able to reproduce in the dap client (VS Code) and with the regular thread client (using rdbg -A).

**Expected behavior**
Backtraces should not take really long times to execute.

### PR DESCRIPTION
**Pull request by dpeacock**
The DAP server doesn't use args and in some instances retrieving these is very slow.  Extracted them into their own methods to prevent this form slowing down DAP requests as the data is not used.
- Relates to #635

### CODE REVIEW

File: lib/debug/frame_info.rb [hunk 1]
```diff
@@ -83,16 +82,23 @@ def frame_type
...
       return unless frame_type == :block
-      args = parameters_info
       _, level, block_loc = location.label.match(BLOCK_LABL_REGEXP).to_a
-      [level || "", block_loc, args]
+      [level || "", block_loc]
+    end
+
+    def block_args
+      return unless frame_type == :block
+      parameters_info
```
Comment (st0012) [inline lib/debug/frame_info.rb:91]: so this and `method_args` actually just calls `parameters_info` 🤔 
I think the frame type check isn't very necessary here because they're not exposed to end users. how about we remove them and just call `parameters_info` from ThreadClient?

**Comment by st0012** [comment]
@dpeacock I don't think it fixes #635. It just excludes DAP users from the problem. But console users will still face it as far as I understand?

**Comment by dpeacock** [comment]
> @dpeacock I don't think it fixes https://github.com/ruby/debug/issues/635. It just excludes DAP users from the problem. But console users will still face it as far as I understand?

Good call-out it just prevents the issue from happening for DAP clients.  Console users will experience it, but at least can specific the depth of the stacktrace from the commandline which the DAP clients currently cannot do.

**Comment by st0012** [comment]
@dpeacock Thanks for the PR 🎉 
@ko1 I think this one looks good and can be merged.

**Comment by st0012** [comment]
@peterzhu2118 Could you give this a look? Thx

**Review by peterzhu2118 — APPROVED** [review]
Looks good, thank you!
