### PR TITLE
No lib deubg

### LINKED ISSUE #275: require 'debug' on `rdbg` without bundle exec will require old `lib/debug`
continue from https://github.com/ruby/debug/issues/261#issuecomment-916422750

```
[master]$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

[master]$ head target.rb -n 5

require 'debug'
p 1

__END__

[master]$ exe/rdbg target.rb -n
DEBUGGER: Session start (pid: 18626)
/home/ko1/.rbenv/versions/2.7.3/lib/ruby/2.7.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Traceback (most recent call last):
        3: from target.rb:2:in `<main>'
        2: from /home/ko1/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        1: from /home/ko1/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/home/ko1/.rbenv/versions/2.7.3/lib/ruby/2.7.0/debug.rb:179:in `<top (required)>': DEBUGGER__ is not a class (TypeError)
/mnt/c/ko1/src/rb/ruby-debug/lib/debug/config.rb:3: previous definition of DEBUGGER__ was here
```

because `lib/debug.rb` is required.

```
[master]$ ruby -v
ruby 3.1.0dev (2021-09-12T09:44:53Z master 11fd3fec53) [x86_64-linux]

[master]$ exe/rdbg target.rb -n
DEBUGGER: Session start (pid: 18915)
/home/ko1/ruby/install/trunk/lib/ruby/3.1.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
<internal:/home/ko1/ruby/install/trunk/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tracer (LoadError)
        from <internal:/home/ko1/ruby/install/trunk/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/ko1/ruby/install/trunk/lib/ruby/3.1.0/debug.rb:8:in `<top (required)>'
        from <internal:/home/ko1/ruby/install/trunk/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/ko1/ruby/install/trunk/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from target.rb:2:in `<main>'
```

On recent version doesn't solve it.

Now I'm trying to fix it but I come up with MRI's bug (maybe)...

### PR DESCRIPTION
**Pull request by ko1**
prevent to load lib/debug.rb

old lib/debug.rb should not be allowed to load.
`require 'debug'` is needed to update the `$LOADED_FEATURE` cache
(maybe it is a workaround for the MRI's issue)

fix #275

### CODE REVIEW

File: lib/debug/session.rb [hunk 1]
```diff
@@ -23,6 +23,10 @@
 require_relative 'breakpoint'
 require_relative 'tracer'
 
+# To prevent loading old lib/debug.rb in Ruby 2.6 to 3.0
+$LOADED_FEATURES << 'debug.rb'
```
Comment (adam12) [inline lib/debug/session.rb:27]: Neat trick.
